### ISSUE TITLE
What can I work on ? (openfoodfacts-kotlin)

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-swift#1]
### First steps
- [ ] Extract parts of the Android app
- [ ] Create a Kotlin package
- [ ] Automate publication 
- [ ] Add tests

### Features to port/implement
- [ ] Multilingual (180 languages are supported)
- [ ] Create users
- [ ] Check if users exist   

###  Features to port/implement READ
- [ ] Product: you can retrieve information about products
- [ ] Product images (get product image by field, size and language, current fields are: Front, Ingredients, Nutrition, Packaging)
- [ ] Additives, Allergens, Environment impact, Ingredient analysis, Nutrient levels, Nutrition facts (incl. micro-nutrients)
- [ ] Language dependant fields (like ingredients, product name, packaging text)
- [ ] Eco-Score, Nutri-Score, NOVA groups
- [ ] Translated, high-level and customizable product information (Attributes)
- [ ] Product completion status
- [ ] Folksonomy Engine (custom properties for products)
- [ ] Open Food Facts Events (Gamification)

###  Features to port/implement PERSONALIZATION
- [ ] Recommended Daily Intakes
- [ ] Translated, high-level and customizable product information (Attributes)
- [ ] Autocompleting for the user inputs, by giving suggestions for (Labels, categories, ingredients, additives, traces ...)

###  Features to port/implement SEARCH
- [ ] search products by tags
- [ ] search products with / without additives
- [ ] search products with keywords
- [ ] Personalized search
- [ ] Search V2
###  Features to port/implement Search V2 - Tag types
- [ ] tag:brands - possible values: infinite, json taxo but no autosuggest
- [ ] tag:categories - possible values: finite, json taxo + autosuggest + partial taxo API
- [ ] tag:packaging - display:packaging - packaging
- [ ] tag:labels - possible values: finite, json taxo + autosuggest + partial taxo API
- [ ] tag:origins - display:origins of ingredients - origins of ingredients
- [ ] tag:manufacturing_places - display:manufacturing or processing places - manufacturing or processing places
- [ ] tag:emb_codes - display:packager codes - packager codes
- [ ] tag:purchase_places - display:purchase places - purchase places
- [ ] tag:stores - display:stores - stores
- [ ] tag:countries - possible values: finite (190), json taxo + autosuggest + partial taxo API
- [ ] tag:ingredients -possible values: finite, json taxo + autosuggest + partial taxo API
- [ ] tag:additives - possible values: finite, json taxo + autosuggest + partial taxo API
- [ ] tag:allergens - possible values: finite, json taxo + autosuggest + partial taxo API
- [ ] tag:traces - possible values: finite, json taxo + autosuggest + partial taxo API
- [ ] tag:nutrition_grades possible values: finite (a,b,c,d,e) , json taxo + autosuggest + partial taxo API
- [ ] #539
- [ ] tag:languages - possible values: finite, json taxo + autosuggest + partial taxo API
- [ ] tag:creator - possible values: infinite - we can't really suggest anything (or we have to rely on the facet)
- [ ] tag:editors - possible values: infinite - we can't really suggest anything (or we have to rely on the facet)
- [ ] tag:states - possible values: finite, json taxo + autosuggest + partial taxo API

###  Features to port/implement WRITE
- [ ] Save product to Open Food Facts 
- [ ] Send images
- [ ] User comments and auth
- [ ] Anonymous photo upload
- [ ] Photo operations (rotate, crop, select, unselect with language awareness)
###  Features to port/implement ML
- [ ] Robotoff support
- [ ] Extract ingredients from ingredients image: User can extract the ingredients text if it is missing

#### OCR
- [ ] Get the OCR of the ingredients photo (for validation purposes)
Open Food Facts uses optical character recognition (OCR) to retrieve nutritional data and other information from the product labels.

Process

- [ ] Capture the barcode of the product where you want to perform the OCR.
- [ ] The Product Opener server software opens the image (process_image=1)
- [ ] Product Opener returns a JSON response. Processing is done using Tesseract or Google Cloud Vision (recommended). The result is often cripped with errors with Tesseract, less with Google Cloud Vision.

Notes: 
* The OCR may contain errors. Encourage your users to correct the output using the ingredients WRITE API. 
* You can also use your own OCR, especially if to plan to send a high number of queries.

Parameters
Test server: https://world.openfoodfacts.org/cgi/ingredients.pl
code=code
id=imagefield
process_image=1
## Roadmap
- [ ] List of new APIs to implement: https://github.com/openfoodfacts/api-documentation/issues
- [ ] New APIs: https://github.com/openfoodfacts/api-documentation/issues?q=is%3Aissue+is%3Aopen+label%3A%22new+api+to+document%22
- [ ] Existing APIs: https://github.com/openfoodfacts/api-documentation/

**Comment by Kedar-27** [comment]
Can I create a base project setup and contribute for hacktoberfest?
